# Single container setup for Railway deployment
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data
    environment:
      - DATA_FILE=/app/data/mnemos_data.json