version: '3.8'

services:
  # Production setup with nginx serving React + proxying to FastAPI
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./data:/app/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATA_FILE=/app/data/mnemos_data.json

volumes:
  data: