# Development setup with separate frontend/backend containers
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app  # Hot reload: mount source code
      - /Users/ns/.config/gcloud:/root/.config/gcloud  # Mount Google Cloud credentials
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
      - GOOGLE_CLOUD_PROJECT=mnemos-web
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Hot reload: mount source code
      - frontend_node_modules:/app/node_modules  # Use named volume for node_modules
    env_file:
      - .env

volumes:
  data:
  frontend_node_modules: